### PR TITLE
Updating to recent google's shooping list

### PR DESCRIPTION
**Pull request by Gismo150**
This module was initially broken. No list was retrieved due to failure during login. 
*Updated puppeteer version
*Fixed login procedure by updating the queryselector of the login button

### CODE REVIEW

**Comment by eouia** [comment]
Thanks for your contribution. 
By the way, I cannot maintain this module anymore. I want to take ownership of this module who has an interest. Do you have an interest?

**Comment by Gismo150** [comment]
Sure, I would like to take it.

**Comment by eouia** [comment]
Ok. Thanks.
First, if you have a forked branch still, first remove it. When the same repository exists from the same network, transferring doesn't work. Remove it and tell me then I'll transfer ownership.

**Comment by Gismo150** [comment]
I removed the fork. Thank you.

**Comment by eouia** [comment]
done. accept it. 
Thanks again. Wish you good luck

**Comment by mamurry1989** [comment]
@Gismo150 I'm having difficulty with getting past the authentication in Chromium. I made it headless = false and Google is blocking the sign-in with a statement of browser not secure. It's opening in a new instance of Chromium which doesn't match the chromium accessed on rpi from the navigation menu at the top (where my google account is already logged in and synced).

Any suggestions on a fix? I'm not wise enough to edit the node_helper.js file to get it open the correct chromium instance (or even as a new tab in a currently open window - that would allow it to continue the script without the need to sign in to the Google account)

Thanks

**Pull request merged**
